[package]
name = "libaquestalk-sys"
description = "Rust ffi for libaquestalk1"
license = "MIT"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.138"
